import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const akshar = localFont({
  src: "./fonts/Akshar-VariableFont_wght.ttf",
  variable: "--font-akshar",
});

const aleo = localFont({
  src: "./fonts/Aleo-VariableFont_wght.ttf",
  variable: "--font-aleo",
});

const aleoItalic = localFont({
  src: "./fonts/Aleo-Italic-VariableFont_wght.ttf",
  variable: "--font-aleo-italic",
});

export const metadata: Metadata = {
  title: "App :3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${akshar.variable} ${aleo.variable} ${aleoItalic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
